### ISSUE TITLE
Couldn't specify a schema for databases such as PostgreSQL

### ISSUE THREAD

**Issue by fenicks** [Netflix/sketchy#31]
SQLalchemy datastore like PostgreSQL supports a schema path.
I try to use connect_args in URI but it doesn't work:
`posgresql://user:pass@host.com:5432/db?connect_args={"schema": "sketchy"}`

It could be nice to support a specific schema.
Thanks.

**Comment by sbehrens** [comment]
Hi @fenicks was this after you added the associated postgres packages to the setup.py file?  If so, would you mind putting the stack trace/errors you're seeing?

**Comment by fenicks** [comment]
Hi @sbehrens, it was after adding `psycopg2` in `setup.py`. `connect_args` is probably not supported with SQLAlchemy `create_engine` signature:
```
(sketchenv) christian@y510p:~/workspace/sketchy$ sketchy_db="postgresql://postgres:postgres@localhost:5432/postgres?connect_args={'schema': 'skecthy'}" python manage.py create_db
/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py:1246: UserWarning: /home/christian/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "manage.py", line 141, in <module>
    manager.run()
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/Flask_Script-2.0.5-py2.7.egg/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/Flask_Script-2.0.5-py2.7.egg/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/Flask_Script-2.0.5-py2.7.egg/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 40, in create_db
    db.create_all()
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/Flask_SQLAlchemy-1.0-py2.7.egg/flask_sqlalchemy/__init__.py", line 856, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/Flask_SQLAlchemy-1.0-py2.7.egg/flask_sqlalchemy/__init__.py", line 848, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), tables=tables)
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/sql/schema.py", line 3352, in create_all
    tables=tables)
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1616, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1609, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1799, in contextual_connect
    self.pool.connect(),
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/pool.py", line 338, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/pool.py", line 641, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/pool.py", line 440, in checkout
    rec = pool._do_get()
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/pool.py", line 961, in _do_get
    return self._create_connection()
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/pool.py", line 285, in _create_connection
    return _ConnectionRecord(self)
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/pool.py", line 411, in __init__
    self.connection = self.__connect()
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/pool.py", line 537, in __connect
    connection = self.__pool._creator()
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/engine/strategies.py", line 96, in connect
    connection_invalidated=invalidated
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/engine/strategies.py", line 90, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/engine/default.py", line 377, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/christian/workspace/sketchy/sketchenv/local/lib/python2.7/site-packages/psycopg2-2.6.1-py2.7-linux-x86_64.egg/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (OperationalError) invalid connection option "connect_args"
 None None
```

**Comment by sbehrens** [comment]
@fenicks Got it, I would encourage you open this ticket with the SQLAlchemy team for a fix.

-Scott

**Comment by fenicks** [comment]
Agreed.
